### PR TITLE
Add basic configuration structure

### PR DESCRIPTION
**Pull request by saschagrunert**
We now utilize the clap crate to parse the CLI parameters into a
configuration structure. This structure derives all getters and can be
later on serialized into a file as well.

Relates to https://github.com/cri-o/cri/issues/5

The help output right now looks like this:
screenshot

### CODE REVIEW

**Comment by saschagrunert** [comment]
/hold 
requires other PRs to be merged, first

**Comment by mrunalp** [comment]
You beat to me to adding clap :D

**Comment by saschagrunert** [comment]
/hold cancel
Requires https://github.com/cri-o/cri/pull/11

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
