### PR TITLE
Remove unwrap in pod sandbox test

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
There is no need to unwrap anywhere, so we can return a result in the test.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by Klaven — COMMENTED** [review]
Never used anyhow before but I looked it up. it seems nice really nice. Question, to me `.unwrap()` seems safe enough in a test right? other then the fact that using `.unwrap()` is considered bad is there anything i'm missing why we might now want it here?

**Comment by saschagrunert** [comment]
> Never used anyhow before but I looked it up. it seems really nice. Question, to me `.unwrap()` seems safe enough in a test right? other then the fact that using `.unwrap()` is considered bad is there anything i'm missing why we might now want it here?

No worries, I’m happy to answer all questions. 🙂

My general rule of thumb is to never use `unwrap()`. The `?` operator is even shorter and correctly populates the error stack. Anyhow provides a `Context` trait (see several uses in the lib), which allows to stack errors with an additional context message. This also works for the `Option` type.

Sooo, yeah it would be “okay” to unwrap in the tests, but this habit can be omitted since test functions can return a `Result` in Rust.

**Review by Klaven — APPROVED** [review]
cool. thanks for the explanation! /lgtm!

**Pull request merged**
