### PR TITLE
Add GitHub actions

### LINKED ISSUE #8: Add basic CI
We can run basic CI checks, like running:
- cargo clippy
- cargo fmt and check the diff
- cargo test

We could either utilize GitHub actions, CircleCI or prow. Which one would you prefer?

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind design

#### What this PR does / why we need it:

Adding some GitHub actions to utilize most of our Makefile targets.

#### Which issue(s) this PR fixes:

Closes #8 
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
Hm, does not seem to run yet…

**Comment by saschagrunert** [comment]
Looks like this is working :shrug: . The two failing tests just depend on the other PRs to be merged. Otherwise I can rebase and we're probably already good to go. WDYT?

**Comment by saschagrunert** [comment]
Rebased for :green_circle:  CI

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
