### PR TITLE
Use Status transformer traits for easier error mapping

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
This allows us to reduce the nose in error handling paths in the GRPC
API.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Review by giuseppe — APPROVED** [review]
LGTM

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by giuseppe** [comment]
do we need two reviews before merging or can we move faster at this point?

**Comment by saschagrunert** [comment]
> do we need two reviews before merging or can we move faster at this point?

Updated the branch protection rule for the master branch. I think you still can drop a `/lgtm` to merge.

**Review by mrunalp — APPROVED** [review]

**Pull request merged**
