### PR TITLE
Rename project to containrs

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
We decided on a name and now we rename the project to `containrs`.

#### Which issue(s) this PR fixes:

Fixes https://github.com/cri-o/cri/issues/27
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
Renamed project to "containrs"
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
After that we also have to rename the repository.

**Comment by haircommander** [comment]
LGTM

**Review by Klaven — COMMENTED** [review]
:+1: awesome name!

**Pull request merged**
